### ISSUE TITLE
The command failed with an unexpected error. Here is the traceback:

### ISSUE THREAD

**Issue by jasweaver** [haithamshahin333/aks-concepts#1]
Make sure you are on the latest version of azure-cli.  I was getting errors on version 2.23.0.  Once I upgraded to 2.24.2 I was able to fully deploy the cluster.

Error:

Creating AKS cluster 'jason-aks' in resource group 'jason-demo-aks-cluster'.
The behavior of this command has been altered by the following extension: aks-preview
The command failed with an unexpected error. Here is the traceback:
'DeploymentsOperations' object has no attribute 'begin_create_or_update'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/jason/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1270, in aks_create
    _ensure_container_insights_for_monitoring(
  File "/Users/jason/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2758, in _ensure_container_insights_for_monitoring
    return _invoke_deployment(cmd, resource_group, deployment_name, template, params,
  File "/Users/jason/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 329, in _invoke_deployment
    return sdk_no_wait(no_wait, smc.begin_create_or_update, resource_group_name, deployment_name, deployment)
AttributeError: 'DeploymentsOperations' object has no attribute 'begin_create_or_update'
To open an issue, please run: 'az feedback'
 
~/Documents/GitHub/aks-concepts on  main ⌚ 17:01:50

**Comment by haithamshahin333** [comment]
Thanks for documenting this @jasweaver! Tracking this issue upstream https://github.com/Azure/azure-cli-extensions/issues/3445 which looks related.

As you mentioned, fix is to update the az cli to the latest version (2.24.x).

adding to the README the prereqs list so others can avoid this error.
